module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  moduleNameMapper: {
    '^src/(.*)$': '<rootDir>/src/$1',
  },
  rootDir: '.',
  testRegex: 'test/.*\\.(spec|test)\\.ts$',
  collectCoverageFrom: [
    'src/**/*.(t|j)s',
    '!src/**/migrations/**',
    '!src/**/*.migration.ts',
    '!src/**/*.module.ts',
    '!src/**/modules.ts',
    '!src/main.ts',
    '!src/environment.ts',
    '!src/environments/**',
    '!src/database/**',
  ],
  testPathIgnorePatterns: [
    '/node_modules/',
    '/dist/',
    '/k8s/',
    '/coverage/',
    '.*\\.module\\.ts$',
    '.*modules\\.ts$',
    '/migrations/',
    '.*migration.*\\.ts$',
    'src/main\\.ts$',
    'src/environment\\.ts$',
  ],
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/dist/',
    '/k8s/',
    'src/main.ts',
    'src/environment.ts',
    'src/environments/',
    'src/migrations/',
    'src/database/',
  ],
  coverageDirectory: './coverage',
  coverageReporters: ['text', 'lcov', 'json-summary', 'html'],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  moduleFileExtensions: ['js', 'json', 'ts'],
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
};
